name: Deploy development

on:
  push:
    branches:
      - master

jobs:
  Development:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        country: [chile, spain]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Deploy
      run: |-
        echo "${{ secret.${{ matrix.country }} }}"
 
