name: test

on:
  pull_request_target:
    types:
      - opened
      - edited
      - ready_for_review
      - synchronize
  issue_comment:
    types: [created, edited]

jobs:
  cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
           - country: chile
             environment: development
             env_file: .env.development.chile 
           - country: spain
             environment: development
             env_file: .env.development.spain
           - country: guatemala
             environment: development
             env_file: .env.development.guatemala
    if: |
      contains(github.event.comment.html_url, '/pull/') && 
      contains(github.event.comment.body, '/deploy ${{ matrix.country }}')    
    steps:
      - name: Message success
        if: ${{ success() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployment succeeded! ✅',
            });

      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployment failed! ❌',
            });

      - name: Message success
        if: ${{ success() }}
        run: |
          curl -s -X POST -H "Content-Type: application/json" -d '${{ env.SLACK_TEXT }}' ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_TEXT: '{ "channel": "#pj-front-deploy", "username": "deploy", "icon_emoji": ":bot:", "text": "Deployment success ${{ secrets[matrix.country] }}!" }'

      - name: Message failure
        if: ${{ failure() }}
        run: |
          curl -s -X POST -H "Content-Type: application/json" -d '${{ env.SLACK_TEXT }}' ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_TEXT: '{ "channel": "#pj-front-deploy", "username": "deploy", "icon_emoji": ":bot:", "text": "Deployment failed ${{ secrets[matrix.country] }}!" }'

