on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment deployment'     
        required: true
        default: 'development' 
        type: choice
        options:
        - development
        - stage
        - production 
      country:
        description: 'Country deployment'     
        required: true
        default: 'chile' 
        type: choice
        options:
        - chile
        - spain
        - costarica
        - portugal
        - guatemala
        - panama

jobs:
  development:
    if: github.event.inputs.environment == 'development'
    runs-on: ubuntu-latest

    steps:
      - name: chile
        if: github.event.inputs.country == 'chile'
        run: |
          echo "chile"
          
      - name: spain
        if: github.event.inputs.country == 'spain'
        run: |
          echo "spain"
