name: 'TEST'

on: 
  workflow_dispatch:
    inputs: 
      country:
        description: 'Country deployment'     
        required: true
        default: 'all' 
        type: choice
        options:
        - chile
        - spain
        - costarica
        - portugal
        - guatemala
        - panama
        - all

jobs:          
  test:
    if: |
      github.event.inputs.country == matrix.country || 
      github.event.inputs.country == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo "${{ matrix.country }}" 
