name: 'TEST'

on: 
  workflow_dispatch:
    inputs: 
      country:
        description: 'Country deployment'     
        required: true
        default: 'all' 
        type: choice
        options:
        - chile
        - spain
        - costarica
        - portugal
        - guatemala
        - panama
        - all

jobs:          
  test:
    strategy:
      matrix:
        include:
          - country: chile
            variable_file: env.development.chile
            variable_secrets: ENV_DEVELOPMENT_CHILE
          - country: spain
            variable_file: env.development.spain
            variable_secrets: ENV_DEVELOPMENT_SPAIN
    runs-on: ubuntu-latest
    steps:
      - name: run
        if: |
          github.event.inputs.country == 'spain' || 
          github.event.inputs.country == 'all'
        run: |
          echo "${{ matrix.country }} ${{ github.event.inputs.country }}" 
