name: 'TEST'

on: 
  workflow_dispatch:
    inputs: 
      country:
        description: 'Country deployment'     
        required: true
        default: 'all' 
        type: choice
        options:
        - chile
        - spain
        - costarica
        - portugal
        - guatemala
        - panama
        - all

jobs:          
  test:
    strategy:
      matrix:
        include:
          - country: chile
            variable_file: env.development.chile
            variable_secrets: ENV_DEVELOPMENT_CHILE
          - country: spain
            variable_file: env.development.spain
            variable_secrets: ENV_DEVELOPMENT_SPAIN


    runs-on: ubuntu-latest
    steps:

      - name: run
        if: |
          github.event.inputs.country == 'spain' || 
          github.event.inputs.country == 'all'
        run: |
          echo spain

      - name: run
        if: |
          github.event.inputs.country == 'chile' || 
          github.event.inputs.country == 'all'
        run: |
          echo chile

      - name: Send a message to Microsoft Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOKS }}
          title: Title
          summary: Helo
          text: Helo 2
          theme_color: 36FF33
          sections: '[{ "activityTitle": "hello world" }]'
          actions: '[{ "@type": "OpenUri", "name": "lorem ipsum", "targets": [{ "os": "default", "uri": "https://localhost" }] }]'          