name: 'TEST'

on: 
  workflow_dispatch:
    inputs: 
      environment:
        description: 'Environment deployment'     
        required: true
        default: 'development' 
        type: choice
        options:
        - development
        - stage
      country:
        description: 'Country deployment'     
        required: true
        default: 'chile' 
        type: choice
        options:
        - chile
        - spain
        - costarica
        - portugal
        - guatemala
        - panama

jobs:
  development:
    if: |
      github.event.inputs.environment == 'development' && 
      startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        include:
          - country: chile
            variable: env.DEVELOPMENT
          - country: spain
            variable: env.DEVELOPMENT

    runs-on: ubuntu-latest
    steps:
      - name: run
        if: |
          github.event.inputs.country == matrix.country && 
          startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "${{ matrix.country }} development" 
          
  stage:
    if: |
      github.event.inputs.environment == 'development' && 
      startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        include:
          - country: chile
            variable: env.DEVELOPMENT
          - country: spain
            variable: env.DEVELOPMENT

    runs-on: ubuntu-latest
    steps:
      - name: run
        if: |
          github.event.inputs.environment == matrix.country && 
          startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "${{ matrix.country }} stage" 
