on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment deployment'     
        required: true
        default: 'development' 
        type: choice
        options:
        - development
        - stage
        - production 
      country:
        description: 'Country deployment'     
        required: true
        default: 'chile' 
        type: choice
        options:
        - chile
        - spain
        - costarica
        - portugal
        - guatemala
        - panama

jobs:
  development:
    if: github.event.inputs.environment == development
    strategy:
      matrix:
        include:
          - country: chile
            variable: env.DEVELOPMENT
          - country: spain
            variable: env.DEVELOPMENT

    runs-on: ubuntu-latest
    steps:
      - name: check
        if: github.event.inputs.country == matrix.country
        run: |
          echo ${{ matrix.country }}
          

